name: casetracking
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  awesome_snackbar_content: ^0.1.7
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  dropdown_button2: ^2.3.9
  mobile_scanner: ^7.1.4
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  hive: ^2.2.3
  shared_preferences: ^2.5.3
  equatable: ^2.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ðŸ‘‡ THIS MUST BE AT ROOT LEVEL
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/app_logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/logo/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
